### PR TITLE
Create docker-publish.yml

### PR DESCRIPTION
**Pull request by Sammy1Am**
Bit of an optional PR depending on how you feel about it (i.e. my feelings won't be hurt if you reject it), but added a GitHub Actions workflow to automatically publish a docker image to ghcr.io to make it easy to update my containers when changes are made to `master`.

### CODE REVIEW

**Comment by snowzach** [comment]
I'm no so good with github actions? Is signing the image just making it better?

**Comment by Sammy1Am** [comment]
If I'm honest, I'm mostly concerned with the auto-publishing so I can add the image from the github repo and just click the "update" button on Unraid :P.

Generally speaking, signing the image authenticates it as coming from a trustworthy source.  If you signed it using your own private key, everyone would know that **you** approve of that image.  In this case it's using ephemeral keys, which I think just means you can trust that the image you think you downloaded from the GitHub repo actually came from the GitHub repo?  It doesn't strike me as hugely important, but to anyone who wants to only use signed images it's a nice freebie.  And for anyone who doesn't care, it doesn't get in the way.

**Comment by snowzach** [comment]
Okay I'll have a think about this one. It takes a looonnnnggg time to build without a build cache and it's likely to be terribly slow in github. I would like to do it at some point. I probably need to setup a bunch of variables in the project no?

**Comment by Sammy1Am** [comment]
It takes about 2-3 minutes on GitHub (you can [check it out in my repo here](https://github.com/Sammy1Am/doods2/actions)), and surprisingly there's nothing to set up other than having the `docker-publish.yml` file.  If you merge this PR, it should kick off a build and you'll have an image published in a couple minutes.  It shows up as a package to the right side of your repo page, and makes it easy for others to [run the container without needing to build their own copy](https://github.com/Sammy1Am/doods2/pkgs/container/doods2).

(Sorry if I sound a little overenthusiastic; I just figured out about this a couple weeks ago and it's been saving me tons of time doing Docker development)

**Comment by snowzach** [comment]
Alright, I'll try it out..

**Pull request merged**
