### PR TITLE
Debian container

### PR DESCRIPTION
**Pull request by Curid**
- [x] amd64
- [x] arm/v7
- [x] arm64/v8
- [x] amd64-noavx
- [x] amd64-gpu

### CODE REVIEW

**Comment by Curid** [comment]
I will add EdgeTPU and then try the ARM builds.

**Comment by snowzach** [comment]
That looks pretty good. I'm sure it's way smaller. If I can come up for air from work stuff I may take another crack at the ARM builds. They are a bear. Basically the Tensorflow people more or less said they are no longer supporting 32 bit arm.

**Comment by Curid** [comment]
Added libedgetpu, just needs some testing then amd64 is done.

Uncompressed size.
Old:  5.14GB
New: 3.74GB

**Comment by Curid** [comment]
The arm64 build just hangs randomly after several hours. No CPU usage and no errors.

**Comment by snowzach** [comment]
Is it in the middle of building tensorflow? Are you cross compiling or using buildx or native? In all cases it's likely running out of memory. You need to pass resources into Bazel (and even then it seems like it ignores it) I would just keep ratcheting down memory and cpu until it completed.

**Comment by Curid** [comment]
I'm using buildx. I guess the emulation uses more memory. The amd64 builds threw errors before I added a swapfile.

Limiting it with `--jobs` seems to work, but now it looks like it's going to take 2 days to build.

**Comment by snowzach** [comment]
I don't think I ever got it to complete using buildx. I finally bought an ODroid C2 I think it was to compile it on.

**Comment by snowzach** [comment]
Wow! I will check it out... Did you use qemu on an x86 box to do the cross builds? If so, what version was qemu?

I ran the armv7 and it came back with `#6 42.20 E: Unable to locate package libabsl-dev` 

Trying out the arm64 one now.

**Comment by Curid** [comment]
Why is there no bazel-bootstrap package for armv7??
https://packages.debian.org/bullseye/bazel-bootstrap

**Comment by Curid** [comment]
I guess we'll have to download binaries manually. https://github.com/bazelbuild/bazel/releases/tag/4.2.1

**Comment by Curid** [comment]
Turns out you can build Bazel from scratch. I didn't see that before.

**Comment by Curid** [comment]
Small fix, bazel doesn't bundle the jdk anymore.

**Pull request closed without merging**
